# Generated by Django 4.2.7 on 2023-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_order_status_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
