# Generated by Django 4.2.7 on 2023-11-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_customeraddress_default"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customeraddress",
            old_name="default",
            new_name="default_address",
        ),
    ]
