# Generated by Django 4.2.7 on 2023-11-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_productrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productrating",
            old_name="revieWs",
            new_name="reviews",
        ),
    ]
