# Generated by Django 4.2.7 on 2023-12-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_customerrating_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unavailable", "Non disponible"),
                    ("Rented", "Déjà loué"),
                    ("Available", "Disponible"),
                ],
                default="Available",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=30)),
                ("stock", models.IntegerField(default=0)),
                ("image_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="main.product",
                    ),
                ),
            ],
        ),
    ]
