# Generated by Django 4.2.7 on 2023-12-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_product_status_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
